name = "azure -infra"
location = "canadacentral"
vnetcidr = "192.168.0.0/16"
websubnetcidr = "192.168.1.0/24"
appsubnetcidr = "192.168.2.0/24"
dbsubnetcidr = "192.168.3.0/24"
web_host_name = "webserver"
web_username = "web_user"
web_os_password = "@Webuser1"
app_host_name = "applicationserver"
app_username = "app_user"
app_os_password = "@Appuser1"
server_name = "server-database"
server_database_admin = "sqladmin"
server_database_password = "pa$$w0rd"
server_version = "11.0"

